BASE_HOST = "https://api.kraken.com"
PUBLIC_URI = f"{BASE_HOST}/0/public"

ASSET_INFO_URI = f"{PUBLIC_URI}/AssetPairs"
TICKER_INFO_URI = f"{PUBLIC_URI}/Ticker"
CANDLE_INFO_URI = f"{PUBLIC_URI}/OHLC"

PRIVATE_PATH = "/0/private"
TRADES_HISTORY_PATH = f"{PRIVATE_PATH}/TradesHistory"
TRADES_HISTORY_URI = f"{BASE_HOST}/{TRADES_HISTORY_PATH}"

OPEN_ORDERS_PATH = f"{PRIVATE_PATH}/OpenOrders"
OPEN_ORDERS_URI = f"{BASE_HOST}/{OPEN_ORDERS_PATH}"
